### ISSUE TITLE
Generate HTML-syntax class names instead of CSS-syntax

### ISSUE THREAD

**Issue by AdamSzakal** [webchun/tachyons-sublime-autocomplete#1]
Since the core idea of Tachyons is to move away from editing CSS-files – why not let the shortcuts generate the class names ready for the markup? For example, "pa3" instead of ".pa3". 

Should save us a lot keyboard-tapping-and-dot-removing.

PS. Stoked that this plugin is happening. 👏

**Comment by webchun** [comment]
Ah yes, my mistake. I have fixed it. Thanks
